# ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█░
# ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀░
# ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░░

format = """
$username\
$hostname\
[](fg:#6791c9 bg:none)\
$directory\
[](fg:#6791c9 bg:#78b892)\
$git_branch\
[](fg:#78b892 bg:#67afc1)\
$git_state\
$git_status\
[](fg:#67afc1 bg:none)\
$character\
"""

right_format = """
$docker_context\
$terraform\
$python\
$php\
$nodejs\
$aws\
$cmd_duration $jobs\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = " [](#6791c9)"
error_symbol = " [](#df5b61)"
vicmd_symbol = "[  ](#78b892)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[](fg:#1c252c bg:none)[$duration]($style)[](fg:#1c252c bg:#1c252c)[](fg:#bc83e3 bg:#1c252c)[ ](fg:#1c252c bg:#bc83e3)[](fg:#bc83e3 bg:none)"
disabled = false
style = "fg:#d9d7d6 bg:#1c252c"

[directory]
format = "[ ](fg:#1c252c bg:#6791c9)[$path]($style)"
style = "fg:#1c252c bg:#6791c9"
truncation_length = 4
truncate_to_repo=false

[git_branch]
format = "[ $branch]($style)[ ](fg:#1c252c bg:#78b892)"
style = "fg:#1c252c bg:#78b892"

[git_status]
format="[ $all_status$ahead_behind]($style)[ ](fg:#1c252c bg:#67afc1)"
style = "fg:#1c252c bg:#67afc1"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "󰄬 "
untracked = "?${count}"
stashed = " "
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "x${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[terraform]
format = '[$symbol$workspace]($style) '

[php]
format = '[$symbol($version )]($style)'

[aws]
format = '- [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = "  "

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '

[python]
symbol = " "
style = "bold green"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[username]
format = '[ $user @ ]($style)'
style_user = "bold dimmed blue"
show_always = false

[jobs]
symbol = " "
style = "bold red"
number_threshold = 2
format = "[$symbol$number]($style)"
